---

- name: Build sdn-base
  docker_image:
    name: sdn-base
    path: '.'
    dockerfile: Dockerfile.base
    tag: latest

- name: Build images
  docker_image:
    name: '{{ item }}'
    path: 'sdn/{{ item }}/build'
    dockerfile: 'Dockerfile'
    pull: false
    tag: latest
  with_items:
    - router
    - controller
    - agent