---

- name: Build sdn-base
  docker_image:
    name: sdn-base
    path: '.'
    dockerfile: Dockerfile.base
    tag: latest

- name: Build router
  docker_image:
    name: router
    path: 'router/'
    dockerfile: 'Dockerfile'
    pull: false
    tag: latest

- name: Build controller
  docker_image:
    name: controller
    path: 'controller/'
    dockerfile: 'Dockerfile'
    pull: false
    tag: latest

- name: Build agent
  docker_image:
    name: agent
    path: 'agent/'
    dockerfile: 'Dockerfile'
    pull: false
    tag: latest