---
- name: Ensures /opt/sdn dir exists
  file: path=/opt/sdn  state=directory

- name: install compose
  pip:
    name: docker-compose
    state: present

- name: Create docker compose
  template:
    src: docker-compose_agent.yml.j2
    dest: "/opt/sdn/docker-compose_agent.yml"

- name: Run docker compose
  docker_service:
    project_src: sdn
    files: "/opt/sdn/docker-compose_agent.yml"
    state: present