---

- hosts: all
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Add latest Python and Ansible PPAs
      shell: "add-apt-repository {{ item }} -y"
      become:  true
      with_items:
        - ppa:jonathonf/python-3.6
        - ppa:ansible/ansible
        - ppa:webupd8team/atom
        - ppa:mystic-mirage/pycharm

    - name: install components
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - python3.6
        - python-pip
        - python-dev
        - build-essential
        - docker.io
        - atom
        - pycharm-community
      become: true

    - name: piping
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-py

      become: true
    - name: pull repo
      git:
        repo: 'https://gitlab.com/Kopka/polibuda.git'
        dest: '/home/vagrant/Desktop/save/sdn'

    - name: run ansible
      shell: 'cd /home/vagrant/Desktop/save/sdn; anisble-playbook -i inv.yml run.yml'

      become: root

